// Change to the relevant directory. Update the following path as necessary.
cd **/initial_analysis

// Remove extraneous variables and save the preliminary results as a CSV. Update the 
import delimited predicted_product_raw, clear
gen wheatprod = round(exp(logwheatprod))
keep county year wheatprod
sort county year
export delimited wheat_prod_predicted_standard, replace

// Do the same for the extra data generated by training the model on the entire labeled dataset
import delimited predicted_product_raw_full, clear
gen wheatprod = round(exp(logwheatprod))
keep county year wheatprod
sort county year
export delimited wheat_prod_predicted_full, replace
